#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -O3 -std=c++20
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -O3 -static-libstdc++ -static-libgcc -static

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -Wall -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB) 
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\libMatrix_alg.a

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O3 -Wall
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB) 
LDFLAGS_RELEASE = $(LDFLAGS) -O3
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\libMatrix_alg.a

OBJ_DEBUG = $(OBJDIR_DEBUG)\\determinant.o $(OBJDIR_DEBUG)\\internal_operators.o $(OBJDIR_DEBUG)\\linalg.o $(OBJDIR_DEBUG)\\operations.o $(OBJDIR_DEBUG)\\specials.o $(OBJDIR_DEBUG)\\validate.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\determinant.o $(OBJDIR_RELEASE)\\internal_operators.o $(OBJDIR_RELEASE)\\linalg.o $(OBJDIR_RELEASE)\\operations.o $(OBJDIR_RELEASE)\\specials.o $(OBJDIR_RELEASE)\\validate.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(AR) rcs $(OUT_DEBUG) $(OBJ_DEBUG)

$(OBJDIR_DEBUG)\\determinant.o: determinant.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c determinant.cpp -o $(OBJDIR_DEBUG)\\determinant.o

$(OBJDIR_DEBUG)\\internal_operators.o: internal_operators.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c internal_operators.cpp -o $(OBJDIR_DEBUG)\\internal_operators.o

$(OBJDIR_DEBUG)\\linalg.o: linalg.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c linalg.cpp -o $(OBJDIR_DEBUG)\\linalg.o

$(OBJDIR_DEBUG)\\operations.o: operations.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c operations.cpp -o $(OBJDIR_DEBUG)\\operations.o

$(OBJDIR_DEBUG)\\specials.o: specials.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c specials.cpp -o $(OBJDIR_DEBUG)\\specials.o

$(OBJDIR_DEBUG)\\validate.o: validate.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c validate.cpp -o $(OBJDIR_DEBUG)\\validate.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(AR) rcs $(OUT_RELEASE) $(OBJ_RELEASE)

$(OBJDIR_RELEASE)\\determinant.o: determinant.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c determinant.cpp -o $(OBJDIR_RELEASE)\\determinant.o

$(OBJDIR_RELEASE)\\internal_operators.o: internal_operators.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c internal_operators.cpp -o $(OBJDIR_RELEASE)\\internal_operators.o

$(OBJDIR_RELEASE)\\linalg.o: linalg.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c linalg.cpp -o $(OBJDIR_RELEASE)\\linalg.o

$(OBJDIR_RELEASE)\\operations.o: operations.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c operations.cpp -o $(OBJDIR_RELEASE)\\operations.o

$(OBJDIR_RELEASE)\\specials.o: specials.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c specials.cpp -o $(OBJDIR_RELEASE)\\specials.o

$(OBJDIR_RELEASE)\\validate.o: validate.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c validate.cpp -o $(OBJDIR_RELEASE)\\validate.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

